document.writeln("<CENTER>");
document.writeln("<HR WIDTH=100% COLOR=Red>");
document.writeln("<H1>WEBSITE PROFILE 'John Due'</H1>");
document.writeln("<HR WIDTH=100% COLOR=red>");
document.writeln("<img src= Jhondue.jpg width=250 height=250>");
document.writeln("</center>");
document.writeln("<ol>");
document.writeln("<li>Nim : 123456789</li>");
document.writeln("<li>Nama : John Due</li>");
document.writeln("<li>Kelas : 01SIFP099</li>");
document.writeln("</ol>");
document.writeln("<ul>");
document.writeln("<li>Program Studi : Sistem Informasi</li>");
document.writeln("<li>Alamat : Jl. Taman Puring, Tangerang Selatan</li>");
document.writeln("<li>Asal Sekolah : SMK ADIYASA INFORMASI</li>");
document.writeln("</ul>");
document.writeln("<ol type=I>");
document.writeln("<li>Jurusan : MULTIMEDIA</li>");
document.writeln("<li>Email : johndue@gmail.com</li>");
document.writeln("<li>Telepon : 0812-1234-5678</li>");
document.writeln("</ol>");
document.writeln("<hr width=100% color=red>");
document.writeln("<center>");
document.writeln("<h3>Design by John Due &copy 2024 Allright Reserved</h3>");
document.writeln("</center>");
document.writeln("<hr width=100% color=red>");
document.writeln("</CENTER>");